<template>
  <div id="mobile" class="mobile">
    <div class="full-container mobile__wrap">
      <div class="mobile__main">
        <div class="mobile__main-desc">
          <p class="mobile__main-desc-tag">mobile friendly</p>
          <h3 class="mobile__main-desc-title">
            Manage your money from anywhere
          </h3>
          <p class="mobile__main-desc-text">
            Gain the tools and knowledge you need to navigate the exciting world
            of crypto.
          </p>
        </div>
        <ul class="mobile__main-cards">
          <MobileCardsItem
            v-for="link in mobileStore.cardsLinks"
            :key="link.id"
            :link="link"
          />
        </ul>
        <a class="mobile__main-get">
          <p class="mobile__main-get-link">Get CrypAppy</p>
          <svg
            class="mobile__main-get-icon"
            width="71"
            height="71"
            viewBox="0 0 71 71"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <rect
              x="13"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              x="39"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              x="65"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              x="13"
              y="13"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              x="39"
              y="13"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              x="65"
              y="13"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              x="13"
              y="26"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              x="39"
              y="26"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              x="65"
              y="26"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              x="13"
              y="39"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              x="39"
              y="39"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              x="65"
              y="39"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              x="13"
              y="52"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              x="39"
              y="52"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              x="65"
              y="52"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              x="13"
              y="65"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              x="39"
              y="65"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              x="65"
              y="65"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect width="5" height="5" fill="#159BE8" fill-opacity="0.4" />
            <rect
              x="52"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              x="26"
              y="13"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              y="26"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              x="52"
              y="26"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              x="26"
              y="39"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              y="52"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              x="52"
              y="52"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              x="26"
              y="65"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              y="13"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              x="26"
              y="26"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              x="52"
              y="39"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              y="65"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              x="26"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              y="39"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              x="52"
              y="65"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              x="52"
              y="13"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
            <rect
              x="26"
              y="52"
              width="5"
              height="5"
              fill="#159BE8"
              fill-opacity="0.4"
            />
          </svg>
        </a>
      </div>
      <div class="mobile__side">
        <img :src="images.mobile1" alt="" class="mobile__side-img" />
        <img :src="images.mobile2" alt="" class="mobile__side-img" />
      </div>
    </div>
  </div>
</template>

<script setup>
import MobileCardsItem from "./MobileCardsItem.vue";
import { useMobile } from "../store/mobile.js";
import { images } from "../utils/images.js";

let mobileStore = useMobile();
</script>
